### ISSUE TITLE
Review booking limits for indiv & group study rooms

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#1007]
Hi @sew268 & @eeh53. For the time being and in your absence, @jpm287, @mrr15 and I made a temporary executive decision to consistently apply the following booking limits:

**Booking Maximum Duration:** 240 minutes
**Duration Limit:** 240 minutes per day
**Window Limit:** 3 days 

A note from our conversation:
> It's still a big improvement for patrons over current capabilities (first come, first serve) but limits the potential for abuse. At least it makes them work harder to game the system.

The individual study spaces previously had a window limit of **14 days**. The group study spaces were reigned in big time. Here's a screenshot of the previous settings.

![Screenshot_2019-09-03 LibCal Edit Category Mann Library - Group Study Spaces](https://user-images.githubusercontent.com/409842/64210288-dfecae00-ce70-11e9-97e4-e216e42077df.png)

Obviously, feel free to change these up as you see fit 😄.

**Comment by sew268** [comment]
@cappadona I think this will work well.  This applies to both the individual and the group study correct?  So all rooms will have a 3 day booking window and each user will be limited to 4 hours per day.  And because these are in different groups, each user would be able to reserve an individual and a group study room once per day for 4 hours, right?

**Comment by cappadona** [comment]
@sew268 Well said...

Yes on all accounts 😄
