### ISSUE TITLE
List of rooms/location for filters

### ISSUE THREAD

**Issue by dbranchini** [cul-it/mann-wagon#176]

**Comment by sew268** [comment]
**Space/Room**
Lobby
Gallery
Mann 100
Mann 102
Stone Classroom
Stern Seminar Room, Mann 160
B30A
B30B

@cappadona - making this list got us thinking a bit more about the CIT labs...I know we aren't pulling the reservation data from CIT's calendar but librarians do book 112 for workshops if Stone is booked and it would be great to have those workshops appear in the feed on the homepage.  So workflow-wise, staff would need to enter those 112 workshops into Booked, correct?  If that is correct, then we'll add 112 and the Mac Lab as locations to the list above.

**Comment by cappadona** [comment]
@sew268 @eeh53 I think a preferred workflow would be to have our staff add 112 workshops to the CU Events Calendar (Localist) via the [public submission form](http://events.cornell.edu/event/create).

Adding the CIT Labs as resources in Booked seems counter-intuitive since Booked is meant for managing reservations and we don't have that luxury for the CIT Labs.

Another option would be to pull reservations/events [directly from LabStats](http://labstats.citlabs.cornell.edu/LabStats/Public/GroupSchedule.aspx?groupId=19) but this seems like a lost cause. When I looked into this several years ago, that data was not available via any public API, and CIT is in the middle of migrating to the vendor hosted LabStats (aka the new LabStats, aka LabStats 6) which doesn't included scheduling at this point.

**Comment by sew268** [comment]
@cappadona ok that sounds fine.  So if the workshop is labeled as a 'workshop or class' in locallist it would appear under the workshops and classes field on the homepage, correct?  And we'd still need to have 112 and the Mac lab as a location filter then, right??

**Comment by cappadona** [comment]
@sara Correct and correct :)

**Comment by tap87** [comment]
@sew268 @eeh53 Are all these rooms going to be in LibCal? I know we are thinking about using r25 for basement classrooms, and right now we have a few test rooms in LibCal.

**Comment by tap87** [comment]
All the rooms that need to be in LibCal are already there, the room names will be udpated when we go live.

**Comment by cappadona** [comment]
Initial list has been identified. Will be implemented in #416.

**Comment by cappadona** [comment]
These should be entered in the back office.

**Comment by sew268** [comment]
Added all event locations and as many alternate names that I could think of! :)
