### ISSUE TITLE
Include urls from API in hours display

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#229]

**Comment by cappadona** [comment]
@tap87 I see your [commit in the drop repo](https://github.com/cul-it/mann_liquid_extensions/commit/2e6255a9c48bbd01ff8d0c107fe88537ee5d25b3), but I don't see see the associated changes in this repo to utilize the location URLs and I thought this issue was meant to cover that as well. Did I misunderstand?

**Comment by tap87** [comment]
@cappadona No, you didn't misunderstand. I was planning to clone the repo again do that, but got busy with meetings, but should be done soon.

**Comment by cappadona** [comment]
No worries...just moving back to the oven for now. Thanks :)

**Comment by tap87** [comment]
@cappadona I just pushed a [commit](https://github.com/cul-it/mann-wagon/commit/361803872509be8a78029517af8555f86ef9a732) to dev for rendering url's. You will need to update the mann_liquid_extensions gem to see the result.

**Comment by cappadona** [comment]
Thanks, @tap87. Just pushed a [commit of my own](https://github.com/cul-it/mann-wagon/commit/ae4804) to help us keep the site synced with the latest state of the gem.

**Comment by tap87** [comment]
Thanks, @cappadona I will do that next time
