### ISSUE TITLE
Create an events page that highlights all current displays and exhibits regardless of location

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#35]
At current page: http://mannlib.cornell.edu/events-exhibits, there is no place for announcing substantive student-generated displays (e.g. the sustainable agriculture videos of last fall or that lovely display of DEA student work--the wall lights, that we had in the lobby that one time). https://issues.library.cornell.edu/browse/MANNWEB-176

**Comment by cappadona** [comment]
@tap87 This could be picked up for the Events implementation via [Localist API](https://confluence.cornell.edu/x/ZAZVC)

**Comment by cappadona** [comment]
Should review #30 User Story as well since it's related.

**Comment by dbranchini** [comment]
- List of all events, exhibits, workshops, and classes in Mann Library for x days is displayed initially
	- Heading should be “Upcoming Events”
	- only pull Mann events
	- link to CU events calendar for all CUL events (month view?)
- Remove counts from filters
- List is sorted by date (ascending) initially, other sort options should include by title
- Dates are headings 
	- Today <small>Tue, May 5, 2015</small> for today and tomorrow, then all remaining todays show date as ddd, mmm, d, yyyy
- List contains the title, time, room, and description of the event.  The description should collapse to a read more/less option.
- Filter by Date - selector is a month calendar view
	- Date becomes heading
- Filter by Type (workshop, class, book talk, exhibit, etc.)
- Filter by Space/Room or Location (lobby, gallery, 160, 100, etc.)
- Filters will work together and each filter (date, type, location) can have up to a single value applied 
        - the events displayed must test true for all applied filters
       - i.e. user first applies "Workshop" for type filter, the app shows upcoming workshops, the user then applies "Stone Classroom" for the location filter and the app updates to show only upcoming workshops scheduled in the Stone Classroom.
- "Clear all filters" should be available as a link or button 
- "Find a space for your event" should also be available (instead of reserve a space)
- "Show more" link at the end of the list to load more ** or ** load more automatically on scroll
- Work with Booked API to pull public reservations and show them alongside CU events
   - Mann staff will be able to set public/private when creating reservations
   - all other reservations are set to public by default
   - duplicates on our events page will be handled by staff setting reservation private in Booked
   - The data from the two APIs would be seamlessly merged for the events page as currently prototyped/defined (a filterable list of events). In other words, there would not be any indication that there are multiple data sources feeding the page behind the scenes. When we tackle the issue of making the events linkable, we will need to decide whether we want to handle that via:
a. additional calls to each API (keep user on Mann site to display event details)
-- OR --
b. simply pass them off to the data source (external link) for the respective event details

**One additional note**: We would not attempt to address duplicate events in any automated or systematic way when merging the data from the two APIs. Tobi, Sara and I discussed this yesterday morning after you and Darcy left. It would be up to Mann staff to remove the duplicate from the Booked API (via setting a public boolean to false). There was brief mention of the duplication handling in my original list, but I just wanted to point it out again. Also, if you have already started looking into the Booked API (see GetReservations) and our requirements matrix (see requirement M), you'll notice that this public/private feature is something we need to implement ourselves.

**Comment by dbranchini** [comment]
![screen shot 2016-04-11 at 2 13 33 pm](https://cloud.githubusercontent.com/assets/6816624/14437533/a383c032-ffef-11e5-84af-f73848996176.png)
