### ISSUE TITLE
Normalize staff photos

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#394]
Can proceed now that I have the photos #389

**Comment by dbranchini** [comment]
Photos were normalized by adjusting the height -- starting with the top so the photo starts just above the head.  I recognize that some are much closer (Keith Jenkins) than others, but there's not much you can do about these.  We can't add more background.  If we wanted all of the photos to look the same, then we'd need to use Keith as the baseline and adjust all of the photos to be that close.  Jenny suggested she retake Keith's photo since that's the one that really stands out.  She was going to reach out to Keith to suggest it.

**Comment by eeh53** [comment]
We need to revisit the rendering when the photos are in circles on the homepage.

**Comment by dbranchini** [comment]
Am I imagining this -- it looks like the images that I normalized might have been changed or maybe it's just the new ones?  The circles weren't cutting people at the throat after I normalized them.

**Comment by cappadona** [comment]
Yes...Tobi uploaded all of Jenny's new photos. Darcy will renormalize.

**Comment by cappadona** [comment]
I believe @dbranchini has re-applied the normalization, although she will have to confirm. There is a second issue (#428) to address new photos/retakes.

**Comment by cappadona** [comment]
@dbranchini Can we consider this baked? We have #428 for any of the new photos/stragglers.
