### ISSUE TITLE
Evaluate Booked, MRBS, LibCal, Sharepoint

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#48]
https://issues.library.cornell.edu/browse/MANNWEB-208. Sub-task of https://issues.library.cornell.edu/browse/MANNWEB-214

**Comment by sew268** [comment]
![booked_libcal_mrbs comparison](https://cloud.githubusercontent.com/assets/14821406/12920460/b39a053a-cf16-11e5-80cb-155c00aaa176.JPG)

**Comment by sew268** [comment]
LibCal evaluation against reservation requirements [https://docs.google.com/spreadsheets/d/1nq5zXXHC8r1XTVfODcq-PAs4jWFizWacZP2CLhcogPw/edit#gid=186001220](url)

**Comment by sew268** [comment]
I've updated the google sheet and added booked with some question marks.  Nick, can you see if you can find answers as well as determine whether the API is what we need?

**Comment by sew268** [comment]
Based on previous work looking at Sharepoint I don't know that Tobi or I can make a determination if Sharepoint is still an option.  If we want to pursue Sharepoint, I think the next step would be sending Chris the reservation workflows - right??  I'm inclined to take Sharepoint off the table,
MRBS the documentation is weak and there have been no updates since October 2015.  It doesn't look much different from the system that we have now.  I suppose if the current bugs (like not sending confirmation emails) could be fixed and we use Timekit to help with the interface it might be worth exploring.

**Comment by cappadona** [comment]
Just added #71 to assess BookedScheduler API and review questions in requirements matrix.

**Comment by cappadona** [comment]
I agree that Sharepoint should be removed from the table.

**Comment by cappadona** [comment]
@sew268 @eeh53 I'm also willing to do a local instance of the current MRBS if you'd like.

I don't think it's fair to assess it purely based on our experiences with our current instance which is running a very old version (that also happens to be significantly modded).

**Comment by sew268** [comment]
Ok - I guess we should do a least that much.

**Comment by cappadona** [comment]
Thanks, not sure if you saw my comments on #71, but I can add issues to get both Booked and MRBS installed on a VM. That work?

**Comment by sew268** [comment]
Didn't see that and yes, that works.

**Comment by sew268** [comment]
Added new issues #81 & #82 to evlaute Booked and MRBS in similar fashion to LibCal
