### ISSUE TITLE
Mediated reservations in LibCal

### ISSUE THREAD

**Issue by sew268** [cul-it/mann-wagon#543]
nail down policy and workflow for Lobby & Stone classroom

**Comment by sew268** [comment]
Tobi & I have discussed this; workflow on staff end is set and policy information in LibCal is now accurate.

In terms of how to display availability for Stone Classroom and the Lobby (the only 2 locations that require mediation) - we think that instead of saying 'available or unavailable', the card for those spaces should say 'Advanced Reservations Required'.  We've adjusted LibCal info so that when you click to make a reservation for either of those spaces the amount of time required in advance for a reservation is much more obvious.

Other suggestions welcome.

**Comment by cappadona** [comment]
Sounds good. I think we should add a boolean field to the `spaces` content type so content editors can indicate that a space requires advanced reservation. When this field is set to true, we would adjust the display logic to render the **Advanced reservations required** message instead of available/unavailable.

I can create the relevant issue(s) if this sounds good unless anyone has any objections.

**Comment by eeh53** [comment]
@cappadona That sounds good to me! I like the idea of giving content editors the ability to control that, since there's always a chance our room reservation policies could change in the future. Thanks!

**Comment by sew268** [comment]
@cappadona yup, sounds good to me too!

**Comment by sew268** [comment]
I think this is baked - Tobi & I have agreed on lead time and workflow

**Comment by sew268** [comment]
Issue #569 is taking care of the advanced reservation message
