### ISSUE TITLE
Populate the LibCal UID field for applicable staff

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#575]
If there's a value for this field that means we'll render the **Book a Consultation** button for this staff member throughout the site. See #322, #372 and #560 for more details.

**Comment by eeh53** [comment]
Done for all Mann staff who have a LibCal UID, including some folks who I suspect I may have to eventually remove, since I doubt they will actually be doing consultations (Greg Lawrence, Liz Brown, Erica Reniff). 

We still need to get a couple of staff members accounts in LibCal and set up with MyScheduler (Matt Ryan and Jeff Piestrak, off the top of my head).

**Comment by sew268** [comment]
Tobi will remove Erica, Liz, etc. Add Matt and then discuss with Keith about GIS.

**Comment by eeh53** [comment]
Update: Sent a message to Keith about GIS and adding Jeff Piestrak. Also added an account for Matt Ryan, and will show him the ropes and how to set up his availability next week.
