### ISSUE TITLE
Split out academic courses from Workshops/Classes

### ISSUE THREAD

**Issue by sew268** [cul-it/mann-wagon#717]
Add a new type like *Academic Course* so we can pull R25 classes out of the "Workshops & Classes" section on the homepage.  This will allow us to highlight library workshops.  *Academic Course* would also then be a filter on the Events Calendar. 

I think we could still call the section on the homepage "Workshops & Classes".  Though I'm waffling on what happens when you click the "Workshops & Classes" button.  @cappadona should that take you to an events page that only shows library workshops prefiltered?  Or would it be both library workshops and R25 classes?  I think the latter makes sense...

**Comment by cappadona** [comment]
@sew268 We can now add a new curated event type in the back-office thanks to Tahir's change in #714 -- he's updated the logic so all R25 events are typed as `Instruction`.

I think the heading for the section on the homepage should match up with the type label we decide to use and would opt to keep our existing headings for our homepage sections, acting very much they way they did prior to the introduction of R25.

As for the event type labels, what do you think of the following?

* **Academic Course** for all R25 events (add a new curated event type and match to `Instruction` string from data source as alternate name)
* **Workshop/Class** to cover what it did before R25 entered the fold

Whatever we decide for labels of these types, I feel pretty strongly about keeping R25 events on their own, because due to their number they will completely overwhelm anything that accompanies them.

**Comment by cappadona** [comment]
Sara and I discussed this and while neither of us are completely in love with the terminology, we're proposing we go with **Academic Course** as a new curated event type for R25 events (catching `Instruction` as an alternate name). I've already setup this new curated event type.

We're also in agreement that we should keep all R25 events in a type of their own, so for now the plan is that there will be no additional alternate names added to **Academic Course**.

We have a few more tricks up our sleeves, and I'm going to create new issues for them -- some of which we'll want to do for the beta release, and others as a top priority immediately thereafter.
