### ISSUE TITLE
Enable academic department content type to have two liaisons

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#794]
Examples: Chris Fournier and Sarah J. Wright share liaison duties for the following departments:
- Biological Statistics and Computational Biology (BSCB)
- Plant Biology (BIOPL)
- Plant Breeding and Genetics (PB&G)

**Comment by cappadona** [comment]
@eeh53 Do Chris and Sarah J share Animal Science as well?

**Comment by eeh53** [comment]
@cappadona This came up again this week. Chris Fournier wants to be linked to her other departments. Can we move this issue up in terms of priority?

Also, I do not believe that Chris and Sarah J. share Animal Science. Sorry I missed that question ;)

**Comment by cappadona** [comment]
Thanks @eeh53, it's top priority for this project, but doesn't rank very high overall 😄. I'll see that it gets a boost and hopefully I'll have good news to report before the end of the week.

**Comment by cappadona** [comment]
Okay @eeh53. Sorry for the delay...quite a bit of changes to our staff over the past year when I initially implemented this, so it took me a while to clear out the cobwebs. Since this has significant impact across multiple models, I've deployed [everything to dev first](http://mannlib-dev.library.cornell.edu/locomotive/benevolent-drylands-8859/preview/help/faculty-instructors/find-your-librarian) as a test run. This includes an example of a department in both colleges as well (#795) -- see DNS.

Let me know what you think once you get a chance to review.

**Comment by cappadona** [comment]
Deployed to [production](https://mannlib.cornell.edu/help/faculty-instructors/find-your-librarian). Chris is now linked to her shared dept =)
