### ISSUE TITLE
Adding folders for photos in Assets

### ISSUE THREAD

**Issue by sew268** [cul-it/mann-wagon#863]
Just added Sandy to the staff list and gave her the place holder photo since she still needs to take one with Jenny.

While searching for the place holder photo, I thought it would be great if it were possible to create folders for photos so we could group event photos, staff photos, space photos, etc.  Rather than having to go page by page to find what you need.  I know you can search but if you don't know the name of the file it's pretty tough.

Not sure if we can do anything about this or if there is a better way?

**Comment by cappadona** [comment]
Hi Sara,

So unfortunately at this point, Locomotive does not offer a way to organize assets into folders. I thought there was an existing issue for asset organization, but I just searched their repos and Trello board and came up empty. We can (and should) add this feature request if it's something that is important to us.

An aside, for this particular use case of selecting a photo for a staff member, you actually don't need to select the placeholder photo. The photo is an optional field for the `staff` content_type and if no photo is selected, the placeholder photo is used by default.

You can see the result in this screenshot. Notice how the placeholder for Deborah is grayed out while the one for Sandy is full opacity? The expected behavior is what is demonstrated for Deborah and this is because if you examine the `content_entry` for her, you'll find that the photo field is empty.

<img width="908" alt="screenshot 2017-04-27 11 23 40" src="https://cloud.githubusercontent.com/assets/409842/25491516/34ec65e0-2b3e-11e7-9bbc-dc01935c281b.png">

I'm going to create an issue to add a hint for the photo field so this default behavior is more obvious.

During the course of reviewing this I also noticed that we do in fact have a photo for Deborah, so I'll add a second issue to optimize that photo and add it to her `content_entry`.
