### ISSUE TITLE
Interim solution: Add link to LibCal public interface for reserving equipment to Equipment page

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#886]
## **Target date: Wed, October 11**

Once the LibCal equipment module is ready to go live, we need to add a link to the equipment page (https://mannlib.cornell.edu/use/technology/equipment) that will redirect patrons to the public interface for the LibCal module. I am open to other suggestions for how we might integrate this into the equipment page, but this seemed like the easiest, fastest solution :)

> See #248 for the discussion around original setup for equipment page

**Comment by cappadona** [comment]
Thanks for the heads up, @eeh53. Two questions:

1. What's the timeline for rolling out equipment reservations via LibCal?
2. Is this the [public interface](http://spaces.library.cornell.edu/equipment.php?lid=96&gid=272) you mention and is the plan to make [all of our equipment](https://mannlib.cornell.edu/use/technology/equipment) reservable?

**Comment by eeh53** [comment]
@cappadona Thanks for checking in on this!

1. I don't really have a timeline yet. I need to circle back to the equipment group to see where things are in terms of prepping the equipment. I think we're pretty solid in terms of procedures at the desk, so let's tentatively say that I would love to roll this out before I leave for vacation (Oct. 12) - but that's definitely flexible.
2. Oops, that link doesn't go anywhere - it just says "file not found". Also, our plan is NOT to make all the equipment reservable. Half will be reservable, half will remain first come, first served.

**Comment by cappadona** [comment]
thanks @eeh53.

We'll shoot for Oct. 12 for this interim solution (providing a link to LibCal Equipment page). The link doesn't work at the moment because we currently have all of our equipment marked as **inactive** in LibCal 😉

**Comment by eeh53** [comment]
@cappadona Aha! I should have known. I think I know what page you're referring to, however (with the little "cards" for the pieces of equipment?) - in which case, yes, that would be the interface I was referring to.

**Comment by cappadona** [comment]
@eeh53 That's the one. Just like [this page for Uris Equipment](http://spaces.library.cornell.edu/equipment?lid=96&gid=217)

**Comment by eeh53** [comment]
@cappadona Yup! I know it's not the best, but I think it will do for now.

**Comment by cappadona** [comment]
Great. Thanks for confirming @eeh53!

**Comment by eeh53** [comment]
@cappadona Quick update: We had a meeting this morning to talk about remaining issues, and things are looking pretty good from our end. We're hoping to launch the reservable equipment service early in the week of Oct. 2. How would that work for you?

**Comment by cappadona** [comment]
Thanks for the update @eeh53. I think @manolobevia and I can make this happen. Is the list of reservable vs loanable equipment in #911 still the latest and greatest?

**Comment by manolobevia** [comment]
Adding a few options:

**Comment by manolobevia** [comment]
Adding a few options:
![reserve link - option 1](https://user-images.githubusercontent.com/8395482/30810950-abdc19c2-a1d4-11e7-9f6b-54106cf752c7.png)
![reserve link - option 2](https://user-images.githubusercontent.com/8395482/30810948-abc702a8-a1d4-11e7-9077-a2fa4dc87165.png)
![reserve link - option 3](https://user-images.githubusercontent.com/8395482/30810949-abce6ba6-a1d4-11e7-9b27-c2c3b657e83a.png)

**Comment by manolobevia** [comment]
Adding a few options:

Option 1
![reserve link - option 1](https://user-images.githubusercontent.com/8395482/30811009-e84ff46e-a1d4-11e7-9dd2-e68b138e6f3e.png)

Option 2
![reserve link - option 2](https://user-images.githubusercontent.com/8395482/30811025-edbd25ca-a1d4-11e7-9e50-d05f86282911.png)

Option 3
![reserve link - option 3](https://user-images.githubusercontent.com/8395482/30811034-f5e6f640-a1d4-11e7-859b-f47e587a84ff.png)

**Comment by cappadona** [comment]
Thanks @manolobevia. The buttons are eye catching but I think we need to do more than just strategic placement of a reserve button _even_ for this interim solution. Our biggest challenge is to clearly convey to our patrons that our equipment falls into two different categories:

1. Loanable (first come, first serve)
1. Reservable (schedule/book/reserve in advance)

There may be differences in policies (can you use a loanable SLR for the same amount of time as a reservable SLR?). I don't have the answers here and am relying on @eeh53 and @jpm287 to set us straight on the policy differences between the two categories.

For a complete list of equipment in each category, please review #911.

> Note that the types of equipment in each category are identical aside from **GPS Units** and the **Thermal Imager** which are loanable **ONLY**

**Comment by eeh53** [comment]
@cappadona and @manolobevia Sorry for the delay on this. I do think it's important to denote that the two types of equipment are separate, since only half the equipment is reservable. My concern with putting on a button on the exisiting equipment page makes it seem as though users are reserving those pieces of equipment (the ones that we're showing availability for), which we're not. That's why I was thinking that having some text that says, "Some of equipment is reservable - click here to reserve" might make that more clear? Thoughts?

As far as loan periods and policies, they are actually the same for both sets of equipment. Loan period is 3 days, the service is only open to CU faculty, staff, and active students, overdue fines are $1.00/minute, etc. Really the only differences are in our procedures for checking the equipment out/in.

**Comment by cappadona** [comment]
Thanks @eeh53. We agree that the current screenshots above are a bit too simplified. We're working on some other options and will be sharing soon.

So the policies for loanable and reservable equipment are identical? Can you elaborate on what you mean when you say?
>  Really the only differences are in our procedures for checking the equipment out/in.

Are you talking about the workflow on the staff side?

One clear difference I see from the patron perspective is this. Let's say I'm in the library, I want a DSLR and I want it now. I check our website and find that we currently have both loanable and reservable DSLRs available at the moment. It might be easier for me to just go to the Circ desk and request a loanable DSLR instead of first having to fill out the reservation form...

**Comment by eeh53** [comment]
@cappadona Yes, the policies are identical. What I meant was that workflows for staff differ during the check in/check out procedure, and for patrons it's really just that the have to book the reservable equipment online. But they still come to the circ desk to check it out, so it's a very similar experience after the reservation is made. The only difference at check out is that we won't make patrons with reservations sign the agreement form (we've incorporated that info into the reservation form through LibCal).

I followed the scenario you laid out above and I totally agree - it may be easier in that case for the patron to bypass making a reservation and just come get the first come, first serve equipment. But I'm not really understanding what you're asking...:/

**Comment by cappadona** [comment]
Ha...thanks for the confirmation @eeh53, and for bearing with me 😄 

Yes, I wasn't asking a question in that scenario, more just giving an example of a difference from the patron perspective, which is what we're striving to emphasize/highlight in both our interim/longterm solutions in creating a world where loanable and reservable equipment can coexist in peace 😉

**Comment by manolobevia** [comment]
@eeh53

**Comment by manolobevia** [comment]
Attaching a mockup for review.
![equipment homepage v3](https://user-images.githubusercontent.com/8395482/30880614-28331564-a2d1-11e7-902a-b2b86884447b.png)

**Comment by jpm287** [comment]
I don't mean this as nitpicking, but looking at this newest mockup, I think the words "Loan" and "Reserve" could offer a source of confusion for patrons. Since technically, all of our equipment is available for loan. This is probably more semantics, but I think the "Loan" buttons should read "Current Availability" or something similar in nature. This way there's more of a distinction between the two categories of 'what can I book in advance' and 'what is available right now.' @eeh53, what do you think? 

However, I really like the idea of the notebox on the righthand side which explains the difference between the two options! The text there could be curated to compliment whatever is ultimately decided upon for the button titles.

With this layout, if a patron clicked the non-reserveable option, what would display - a snippet of the existing equipment webpage with the due dates/item status? And would that be a in-page popup or a new webpage?

**Comment by manolobevia** [comment]
Added minor changes in copy and order of link buttons.
![equipment homepage v4](https://user-images.githubusercontent.com/8395482/30882614-8a4ae4d8-a2d7-11e7-8227-a1b0b5ef8197.png)

**Comment by cappadona** [comment]
Hey @jpm287. Thanks for chiming in and not nitpicky at all.

Based on my observations from interviewing patrons and conducting usability testing of the Mann website and other CUL applications over the past decade, I would agree that the concepts behind **reserve** and **loan** are a source of confusion for a significant percentage of our patrons 😄

I'd like to forego the slicing and dicing of semantics involved to explain that even when reserving, you're _technically_ loaning. It sounds like you are a fan of our proposed approach to help patrons distinguish between these two terms, if we stick with them. Would you prefer to see us continue down this road or should we explore replacing **Loan** with something like:

1. Pickup Now
1. Checkout Now
1. ??

I hesitate to use **Available Now** (or **Current Availability** as you suggested) since _technically_ there could be reservable equipment available at the moment (you just need to reserve them first). Let us know what you think and remember that this is just an interim solution that we can have ready in time for next Monday's launch ;)

@eeh53 Feel free to weigh in as well. Thanks.

**Comment by cappadona** [comment]
@jpm287 P.S. To answer your question, clicking on **Loan** will take the user to [a new page on our site with full details on the equipment](http://mannlib.cornell.edu/use/technology/equipment/cameras), including availability, similar to how we currently handle equipment. Clicking on the **Reserve** button will take the user to the [LibCal public page](http://spaces.library.cornell.edu/equipment?lid=96&gid=365) for that equipment category [1].

Again, I'm describing the interim solution that will hold us over until we [fully integrate the reservable equipment via the LibCal API](https://github.com/cul-it/mann-wagon/issues/913).

> [1] I'm linking to Uris DSLR in this example since all of our equipment is currently inactive/disabled.

**Comment by eeh53** [comment]
Hi @cappadona @jpm287 and @manolobevia!

Wow, this is looking beautiful! I agree that the "loan" vs. "reserve" concepts are confusing for patrons, so maybe using different language would make this more clear. I'm not sure what the best language would be. Like Nick, I hesitate to say "Available Now", because even though it's first come, first served, there may not actually be any DSLRs available at that particular time. 

I think I would be in favor of "Pickup Now" and "Reserve" (would "Reserve for Later" or "Reserve in Advance" be too much?). I like the idea of the the buttons taking you to the info/availability pages for the specific types of equipment, or to the LibCal public reservation page, as appropriate. Would this new layout mean that this page would no longer be on the site: https://mannlib.cornell.edu/use/technology/equipment? Does that long list of all the equipment go away? I'm fine with that if yes, just curious.

**Comment by cappadona** [comment]
Thanks @eeh53.

Okay, so let's go with **Pickup Now** & **Reserve** (I agree it's better to keep it short & sweet). Using these terms probably means we can drop the **Should I Reserve or Loan?** callout entirely. Everyone okay with that?

And yes, this is a mockup to replace the [current equipment page](https://mannlib.cornell.edu/use/technology/equipment). Manolo and I discussed it and thought it was best to drop the full listing of loanable equipment since we'd have to explain that this isn't all the equipment, just some...

**Comment by eeh53** [comment]
@cappadona That sounds good. You can either drop the call out, or - if you think it would be helpful to patrons to explain the difference - we could change the text to:

_Should I make a reservation?
The same borrowing policies apply for both the reservable and first come, first served equipment. The main difference is you can come to the circ desk to pick up any available equipment on the spot, without first reserving it online. If, however, you need a piece of equipment on a specific date, then we would encourage you to make a reservation._

**Comment by cappadona** [comment]
@eeh53 I like it...I think we'll give something like that a shot.

Also, just confirming that the new target date is **Wed, October 11**. Thanks!

**Comment by manolobevia** [comment]
@cappadona @eeh53 @jpm287 
I have updated the Equipment wireframe with the latest changes.
![equipments-v6](https://user-images.githubusercontent.com/8395482/30977313-34b5de00-a445-11e7-99c6-8a4ead2cb9d8.png)
 Thanks

**Comment by eeh53** [comment]
@manolobevia This looks great to me!

**Comment by manolobevia** [comment]
@eeh53 Thanks

**Comment by cappadona** [comment]
Everything on our end has been deployed to production in #924:
http://mannlib.cornell.edu/use/technology/equipment

@sew268 & @jpm287 will be updating the copy and photos for each of the equipment category pages tomorrow.

**Comment by cappadona** [comment]
So close...@sew268 has updated the equipment pages. Now we just need @jpm287 to add the thermal imager to libservices

**Comment by cappadona** [comment]
Thermal imager is all set so pulling this out of the oven. Thanks to everyone for solid team effort 💯
